server:
  port: 8085
spring:
  application:
    name: LMS-SPRING-CLOUD-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: BOOK-SERVICE
          uri: http://book-service:8081
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: LOAN-SERVICE
          uri: http://loan-service:8083
          predicates:
            - Path=/loan-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: RESERVATION-SERVICE
          uri: http://reservation-service:8084
          predicates:
            - Path=/reservation-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: AUTHENTICATOR-SERVICE
          uri: http://authenticator-service:8091
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Auth
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: MEMBER-SERVICE
          uri: http://member-service:8082
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: NOTIFICATION-SERVICE
          uri: http://notification-service:8087
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

eureka:
  client:
    service-url:
#      defaultZone : http://discovery-service:8761/eureka/
      defaultZone: http://host.docker.internal:8761/eureka/