server:
  port: 8085
spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/book-service/(?<segment>.*), /${segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan-service/**
          filters:
            - RewritePath=/loan-service/(?<segment>.*), /${segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: RESERVATION-SERVICE
          uri: http://reservation-service:8084
          predicates:
            - Path=/reservation-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: authenticator-service
          uri: lb://authenticator-service
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /${segment}

            - name: Auth
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: MEMBER-SERVICE
          uri: http://member-service:8082
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

        - id: NOTIFICATION-SERVICE
          uri: http://notification-service:8087
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: true

eureka:
  client:
    service-url:
#      defaultZone : http://localhost:8761/eureka/
      defaultZone: http://host.docker.internal:8761/eureka/